services:
  core-service:
    build:
      context: ./services/core-service
      dockerfile: Dockerfile

    container_name: core-service

    command: uv run python manage.py runserver 0.0.0.0:8000
    
    ports:
      - "8000:8000"

    env_file:
      - ./.env

    depends_on:
      - postgres

    restart: unless-stopped

  postgres:
    image: postgres:18
    restart: always
    
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_USER: ${DB_USER}
    ports:
     - "5433:5432"

  
