# Generated by Django 6.1.1 on 2026-09-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Banned', 'banned'), ('In_verification', 'in_verification')], default='Active'),
        ),
    ]
